### ISSUE TITLE
Change conversation height calculation from Javascript to CSS

### ISSUE THREAD

**Issue by marc-farre** [humhub/mail#406]
The conversation HTML element height is calculated in real time with JavaScript:

![image](https://github.com/user-attachments/assets/de56e0fe-43da-4729-9499-8c9c082bf07f)

With this function: https://github.com/humhub/mail/blob/master/resources/js/humhub.mail.ConversationView.js#L378-L404

This function could be removed if we have the following LESS code:

```less
#mail-conversation-root > .panel {
    display: flex;
    flex-direction: column;
    height: calc(100vh - 165px); // 165px depends on the top menu and should be adpated for different screen width using the @media rule
    
    > .panel-body {
        flex: 1;
        min-height: 150px;
        overflow: auto;
    }

    .mail-message-form {
        .content-create-input-group {
            position: relative;
        }
    }
}
```

For testing, we need to overwrite existing LESS code which should be removed:

```less
    .conversation-entry-list {
        max-height: none;
        height: auto;
        overflow: unset;
    }

    .mail-message-form {
        position: static;
    }
```

Benefits:
- More reliable
- Instant height resizing when adding new lines in the reply form
- Reduced processor resource consumption
- possibility to change the height calculation in custom theme by overwriting the `height: calc(100vh - 165px);`

This would solve the issue we currently have with the Clean Theme on mobile, where the bottom bar is displayed on top of the reply form.
